spring.application.name=segundo-parcial
server.port=8081

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

app.jwt.secret=second-parcial-dev-secret-key-change-me-second-parcial-dev-secret-key-change-me
app.jwt.expiration-ms=86400000
